# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Open GitHub pull request"
  lane :pr do |options|
    branch_name = options.fetch(:branch_name, "release")
    framework_version = get_framework_version

    # Set Podspec version
    version_file = {
      "version" => "v#{framework_version}"
    }

    File.write("../version.json", version_file.to_json)

    # Commit and push changes
    sh "git checkout -b #{branch_name}"

    path = [
      "./*.xcframework/*",
      "./version.json"
    ]

    git_add(
      path: path
    )

    git_commit(
      path: path,
      message: "Release #{framework_version}"
    )

    push_to_git_remote(
      force: true,
      local_branch: branch_name,
      remote_branch: branch_name
    )

    # Open pull request
    github_api(
      server_url: "https://api.github.com",
      api_token: ENV["GITHUB_TOKEN"],
      http_method: "POST",
      path: "/repos/appier/appier-ios-framework/pulls",
      body: {
        "head": branch_name,
        "base": "master",
        "title": "Release v#{framework_version}"
      }
    )
  end

  desc "Deploy AppierFramework Podspecs to CocoaPods Trunk"
  lane :pods_framework do
    Dir.chdir("..") do
      sh "pod trunk push AppierFramework.podspec --allow-warnings"
    end
  end

  desc "Deploy AppierExtensionFramework Podspecs to CocoaPods Trunk"
  lane :pods_extension_framework do
    Dir.chdir("..") do
      sh "pod trunk push AppierExtensionFramework.podspec --allow-warnings"
    end
  end

  desc "Create release on GitHub"
  lane :release do
    framework_version = get_framework_version
    tag = "v#{framework_version}"
    archive_name = "AppierFramework.zip"

    Dir.chdir("..") do
      sh "zip -r #{archive_name} Appier.xcframework AppierExtension.xcframework"
    end

    github_release = set_github_release(
      repository_name: "appier/appier-ios-framework",
      api_token: ENV["GITHUB_TOKEN"],
      name: "Appier iOS SDK #{framework_version}",
      tag_name: tag,
      description: "For details about this release, see the <a href=\"https://docs.aiqua.appier.com/docs/release-notes-for-ios\">release notes</a>.",
      commitish: "master",
      upload_assets: [
        archive_name
      ]
    )
  end

  private_lane :get_framework_version do
    plist_file = "../Appier.xcframework/ios-arm64/Appier.framework/Info.plist"
    sh("/usr/libexec/PlistBuddy #{plist_file} -c 'Print :CFBundleShortVersionString'").strip
  end

end
